name: Test and build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 23.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test --if-present

  publish-main-image:
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        node-version: [ 23.x ]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish staging docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/norkator/poker-pocket-ts-backend:latest
          build-args: NODE_ENV=staging
          file: Dockerfile

  deploy-staging:
    needs: [ tests, publish-main-image ]
    runs-on: ubuntu-latest
    steps:
      - uses: sekassel-research/actions-rancher-update@v3.3.0
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.CLUSTER_ID }}
          namespace: ${{ secrets.NAMESPACE }}
          kind: deployment
          workload: ${{ secrets.WORKLOAD }}
          docker_image: ghcr.io/norkator/poker-pocket-ts-backend:latest

  publish-tagged-image:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        node-version: [ 23.x ]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish docker image for release tag
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/norkator/poker-pocket-ts-backend:${{ github.ref_name }}
          build-args: NODE_ENV=production
          file: Dockerfile
